package com.campus2company.notification.model;

public enum NotificationType {
    NEW_MESSAGE,
    ACCOUNT_APPROVED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_ACTIVATED,
    APPLICATION_SUBMITTED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    APPLICATION_WITHDRAWN
}
